// Code generated by entc, DO NOT EDIT.

package seat

import (
	"airbound/internal/ent/enums"
	"airbound/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// SeatNumber applies equality check predicate on the "seat_number" field. It's identical to SeatNumberEQ.
func SeatNumber(v int) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSeatNumber), v))
	})
}

// SeatRow applies equality check predicate on the "seat_row" field. It's identical to SeatRowEQ.
func SeatRow(v string) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSeatRow), v))
	})
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// SeatNumberEQ applies the EQ predicate on the "seat_number" field.
func SeatNumberEQ(v int) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSeatNumber), v))
	})
}

// SeatNumberNEQ applies the NEQ predicate on the "seat_number" field.
func SeatNumberNEQ(v int) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSeatNumber), v))
	})
}

// SeatNumberIn applies the In predicate on the "seat_number" field.
func SeatNumberIn(vs ...int) predicate.Seat {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Seat(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldSeatNumber), v...))
	})
}

// SeatNumberNotIn applies the NotIn predicate on the "seat_number" field.
func SeatNumberNotIn(vs ...int) predicate.Seat {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Seat(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldSeatNumber), v...))
	})
}

// SeatNumberGT applies the GT predicate on the "seat_number" field.
func SeatNumberGT(v int) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSeatNumber), v))
	})
}

// SeatNumberGTE applies the GTE predicate on the "seat_number" field.
func SeatNumberGTE(v int) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSeatNumber), v))
	})
}

// SeatNumberLT applies the LT predicate on the "seat_number" field.
func SeatNumberLT(v int) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSeatNumber), v))
	})
}

// SeatNumberLTE applies the LTE predicate on the "seat_number" field.
func SeatNumberLTE(v int) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSeatNumber), v))
	})
}

// SeatRowEQ applies the EQ predicate on the "seat_row" field.
func SeatRowEQ(v string) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSeatRow), v))
	})
}

// SeatRowNEQ applies the NEQ predicate on the "seat_row" field.
func SeatRowNEQ(v string) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSeatRow), v))
	})
}

// SeatRowIn applies the In predicate on the "seat_row" field.
func SeatRowIn(vs ...string) predicate.Seat {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Seat(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldSeatRow), v...))
	})
}

// SeatRowNotIn applies the NotIn predicate on the "seat_row" field.
func SeatRowNotIn(vs ...string) predicate.Seat {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Seat(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldSeatRow), v...))
	})
}

// SeatRowGT applies the GT predicate on the "seat_row" field.
func SeatRowGT(v string) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSeatRow), v))
	})
}

// SeatRowGTE applies the GTE predicate on the "seat_row" field.
func SeatRowGTE(v string) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSeatRow), v))
	})
}

// SeatRowLT applies the LT predicate on the "seat_row" field.
func SeatRowLT(v string) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSeatRow), v))
	})
}

// SeatRowLTE applies the LTE predicate on the "seat_row" field.
func SeatRowLTE(v string) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSeatRow), v))
	})
}

// SeatRowContains applies the Contains predicate on the "seat_row" field.
func SeatRowContains(v string) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldSeatRow), v))
	})
}

// SeatRowHasPrefix applies the HasPrefix predicate on the "seat_row" field.
func SeatRowHasPrefix(v string) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldSeatRow), v))
	})
}

// SeatRowHasSuffix applies the HasSuffix predicate on the "seat_row" field.
func SeatRowHasSuffix(v string) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldSeatRow), v))
	})
}

// SeatRowEqualFold applies the EqualFold predicate on the "seat_row" field.
func SeatRowEqualFold(v string) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldSeatRow), v))
	})
}

// SeatRowContainsFold applies the ContainsFold predicate on the "seat_row" field.
func SeatRowContainsFold(v string) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldSeatRow), v))
	})
}

// SeatTypeEQ applies the EQ predicate on the "seat_type" field.
func SeatTypeEQ(v enums.SeatType) predicate.Seat {
	vc := v
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSeatType), vc))
	})
}

// SeatTypeNEQ applies the NEQ predicate on the "seat_type" field.
func SeatTypeNEQ(v enums.SeatType) predicate.Seat {
	vc := v
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSeatType), vc))
	})
}

// SeatTypeIn applies the In predicate on the "seat_type" field.
func SeatTypeIn(vs ...enums.SeatType) predicate.Seat {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Seat(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldSeatType), v...))
	})
}

// SeatTypeNotIn applies the NotIn predicate on the "seat_type" field.
func SeatTypeNotIn(vs ...enums.SeatType) predicate.Seat {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Seat(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldSeatType), v...))
	})
}

// SeatClassEQ applies the EQ predicate on the "seat_class" field.
func SeatClassEQ(v enums.SeatClass) predicate.Seat {
	vc := v
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSeatClass), vc))
	})
}

// SeatClassNEQ applies the NEQ predicate on the "seat_class" field.
func SeatClassNEQ(v enums.SeatClass) predicate.Seat {
	vc := v
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSeatClass), vc))
	})
}

// SeatClassIn applies the In predicate on the "seat_class" field.
func SeatClassIn(vs ...enums.SeatClass) predicate.Seat {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Seat(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldSeatClass), v...))
	})
}

// SeatClassNotIn applies the NotIn predicate on the "seat_class" field.
func SeatClassNotIn(vs ...enums.SeatClass) predicate.Seat {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Seat(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldSeatClass), v...))
	})
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Seat {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Seat(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Seat {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Seat(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Seat {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Seat(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Seat {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Seat(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUpdatedAt), v))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Seat) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Seat) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Seat) predicate.Seat {
	return predicate.Seat(func(s *sql.Selector) {
		p(s.Not())
	})
}
