// Code generated by entc, DO NOT EDIT.

package ent

import (
	"airbound/internal/ent/aircraft"
	"airbound/internal/ent/airline"
	"airbound/internal/ent/crew"
	"airbound/internal/ent/pilot"
	"airbound/internal/ent/predicate"
	"context"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AirlineUpdate is the builder for updating Airline entities.
type AirlineUpdate struct {
	config
	hooks    []Hook
	mutation *AirlineMutation
}

// Where appends a list predicates to the AirlineUpdate builder.
func (au *AirlineUpdate) Where(ps ...predicate.Airline) *AirlineUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetName sets the "name" field.
func (au *AirlineUpdate) SetName(s string) *AirlineUpdate {
	au.mutation.SetName(s)
	return au
}

// SetIataCode sets the "iata_code" field.
func (au *AirlineUpdate) SetIataCode(s string) *AirlineUpdate {
	au.mutation.SetIataCode(s)
	return au
}

// SetCreatedAt sets the "created_at" field.
func (au *AirlineUpdate) SetCreatedAt(t time.Time) *AirlineUpdate {
	au.mutation.SetCreatedAt(t)
	return au
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (au *AirlineUpdate) SetNillableCreatedAt(t *time.Time) *AirlineUpdate {
	if t != nil {
		au.SetCreatedAt(*t)
	}
	return au
}

// SetUpdatedAt sets the "updated_at" field.
func (au *AirlineUpdate) SetUpdatedAt(t time.Time) *AirlineUpdate {
	au.mutation.SetUpdatedAt(t)
	return au
}

// AddAircraftIDs adds the "aircrafts" edge to the Aircraft entity by IDs.
func (au *AirlineUpdate) AddAircraftIDs(ids ...uuid.UUID) *AirlineUpdate {
	au.mutation.AddAircraftIDs(ids...)
	return au
}

// AddAircrafts adds the "aircrafts" edges to the Aircraft entity.
func (au *AirlineUpdate) AddAircrafts(a ...*Aircraft) *AirlineUpdate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return au.AddAircraftIDs(ids...)
}

// AddCrewIDs adds the "crews" edge to the Crew entity by IDs.
func (au *AirlineUpdate) AddCrewIDs(ids ...uuid.UUID) *AirlineUpdate {
	au.mutation.AddCrewIDs(ids...)
	return au
}

// AddCrews adds the "crews" edges to the Crew entity.
func (au *AirlineUpdate) AddCrews(c ...*Crew) *AirlineUpdate {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return au.AddCrewIDs(ids...)
}

// AddPilotIDs adds the "pilots" edge to the Pilot entity by IDs.
func (au *AirlineUpdate) AddPilotIDs(ids ...uuid.UUID) *AirlineUpdate {
	au.mutation.AddPilotIDs(ids...)
	return au
}

// AddPilots adds the "pilots" edges to the Pilot entity.
func (au *AirlineUpdate) AddPilots(p ...*Pilot) *AirlineUpdate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return au.AddPilotIDs(ids...)
}

// Mutation returns the AirlineMutation object of the builder.
func (au *AirlineUpdate) Mutation() *AirlineMutation {
	return au.mutation
}

// ClearAircrafts clears all "aircrafts" edges to the Aircraft entity.
func (au *AirlineUpdate) ClearAircrafts() *AirlineUpdate {
	au.mutation.ClearAircrafts()
	return au
}

// RemoveAircraftIDs removes the "aircrafts" edge to Aircraft entities by IDs.
func (au *AirlineUpdate) RemoveAircraftIDs(ids ...uuid.UUID) *AirlineUpdate {
	au.mutation.RemoveAircraftIDs(ids...)
	return au
}

// RemoveAircrafts removes "aircrafts" edges to Aircraft entities.
func (au *AirlineUpdate) RemoveAircrafts(a ...*Aircraft) *AirlineUpdate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return au.RemoveAircraftIDs(ids...)
}

// ClearCrews clears all "crews" edges to the Crew entity.
func (au *AirlineUpdate) ClearCrews() *AirlineUpdate {
	au.mutation.ClearCrews()
	return au
}

// RemoveCrewIDs removes the "crews" edge to Crew entities by IDs.
func (au *AirlineUpdate) RemoveCrewIDs(ids ...uuid.UUID) *AirlineUpdate {
	au.mutation.RemoveCrewIDs(ids...)
	return au
}

// RemoveCrews removes "crews" edges to Crew entities.
func (au *AirlineUpdate) RemoveCrews(c ...*Crew) *AirlineUpdate {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return au.RemoveCrewIDs(ids...)
}

// ClearPilots clears all "pilots" edges to the Pilot entity.
func (au *AirlineUpdate) ClearPilots() *AirlineUpdate {
	au.mutation.ClearPilots()
	return au
}

// RemovePilotIDs removes the "pilots" edge to Pilot entities by IDs.
func (au *AirlineUpdate) RemovePilotIDs(ids ...uuid.UUID) *AirlineUpdate {
	au.mutation.RemovePilotIDs(ids...)
	return au
}

// RemovePilots removes "pilots" edges to Pilot entities.
func (au *AirlineUpdate) RemovePilots(p ...*Pilot) *AirlineUpdate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return au.RemovePilotIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AirlineUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	au.defaults()
	if len(au.hooks) == 0 {
		if err = au.check(); err != nil {
			return 0, err
		}
		affected, err = au.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AirlineMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = au.check(); err != nil {
				return 0, err
			}
			au.mutation = mutation
			affected, err = au.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(au.hooks) - 1; i >= 0; i-- {
			if au.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = au.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, au.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (au *AirlineUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AirlineUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AirlineUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (au *AirlineUpdate) defaults() {
	if _, ok := au.mutation.UpdatedAt(); !ok {
		v := airline.UpdateDefaultUpdatedAt()
		au.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (au *AirlineUpdate) check() error {
	if v, ok := au.mutation.Name(); ok {
		if err := airline.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf("ent: validator failed for field \"name\": %w", err)}
		}
	}
	if v, ok := au.mutation.IataCode(); ok {
		if err := airline.IataCodeValidator(v); err != nil {
			return &ValidationError{Name: "iata_code", err: fmt.Errorf("ent: validator failed for field \"iata_code\": %w", err)}
		}
	}
	return nil
}

func (au *AirlineUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   airline.Table,
			Columns: airline.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: airline.FieldID,
			},
		},
	}
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: airline.FieldName,
		})
	}
	if value, ok := au.mutation.IataCode(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: airline.FieldIataCode,
		})
	}
	if value, ok := au.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: airline.FieldCreatedAt,
		})
	}
	if value, ok := au.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: airline.FieldUpdatedAt,
		})
	}
	if au.mutation.AircraftsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   airline.AircraftsTable,
			Columns: []string{airline.AircraftsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: aircraft.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedAircraftsIDs(); len(nodes) > 0 && !au.mutation.AircraftsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   airline.AircraftsTable,
			Columns: []string{airline.AircraftsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: aircraft.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.AircraftsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   airline.AircraftsTable,
			Columns: []string{airline.AircraftsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: aircraft.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.CrewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   airline.CrewsTable,
			Columns: []string{airline.CrewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: crew.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedCrewsIDs(); len(nodes) > 0 && !au.mutation.CrewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   airline.CrewsTable,
			Columns: []string{airline.CrewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: crew.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.CrewsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   airline.CrewsTable,
			Columns: []string{airline.CrewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: crew.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.PilotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   airline.PilotsTable,
			Columns: []string{airline.PilotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: pilot.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedPilotsIDs(); len(nodes) > 0 && !au.mutation.PilotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   airline.PilotsTable,
			Columns: []string{airline.PilotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: pilot.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.PilotsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   airline.PilotsTable,
			Columns: []string{airline.PilotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: pilot.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{airline.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// AirlineUpdateOne is the builder for updating a single Airline entity.
type AirlineUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AirlineMutation
}

// SetName sets the "name" field.
func (auo *AirlineUpdateOne) SetName(s string) *AirlineUpdateOne {
	auo.mutation.SetName(s)
	return auo
}

// SetIataCode sets the "iata_code" field.
func (auo *AirlineUpdateOne) SetIataCode(s string) *AirlineUpdateOne {
	auo.mutation.SetIataCode(s)
	return auo
}

// SetCreatedAt sets the "created_at" field.
func (auo *AirlineUpdateOne) SetCreatedAt(t time.Time) *AirlineUpdateOne {
	auo.mutation.SetCreatedAt(t)
	return auo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (auo *AirlineUpdateOne) SetNillableCreatedAt(t *time.Time) *AirlineUpdateOne {
	if t != nil {
		auo.SetCreatedAt(*t)
	}
	return auo
}

// SetUpdatedAt sets the "updated_at" field.
func (auo *AirlineUpdateOne) SetUpdatedAt(t time.Time) *AirlineUpdateOne {
	auo.mutation.SetUpdatedAt(t)
	return auo
}

// AddAircraftIDs adds the "aircrafts" edge to the Aircraft entity by IDs.
func (auo *AirlineUpdateOne) AddAircraftIDs(ids ...uuid.UUID) *AirlineUpdateOne {
	auo.mutation.AddAircraftIDs(ids...)
	return auo
}

// AddAircrafts adds the "aircrafts" edges to the Aircraft entity.
func (auo *AirlineUpdateOne) AddAircrafts(a ...*Aircraft) *AirlineUpdateOne {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return auo.AddAircraftIDs(ids...)
}

// AddCrewIDs adds the "crews" edge to the Crew entity by IDs.
func (auo *AirlineUpdateOne) AddCrewIDs(ids ...uuid.UUID) *AirlineUpdateOne {
	auo.mutation.AddCrewIDs(ids...)
	return auo
}

// AddCrews adds the "crews" edges to the Crew entity.
func (auo *AirlineUpdateOne) AddCrews(c ...*Crew) *AirlineUpdateOne {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return auo.AddCrewIDs(ids...)
}

// AddPilotIDs adds the "pilots" edge to the Pilot entity by IDs.
func (auo *AirlineUpdateOne) AddPilotIDs(ids ...uuid.UUID) *AirlineUpdateOne {
	auo.mutation.AddPilotIDs(ids...)
	return auo
}

// AddPilots adds the "pilots" edges to the Pilot entity.
func (auo *AirlineUpdateOne) AddPilots(p ...*Pilot) *AirlineUpdateOne {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return auo.AddPilotIDs(ids...)
}

// Mutation returns the AirlineMutation object of the builder.
func (auo *AirlineUpdateOne) Mutation() *AirlineMutation {
	return auo.mutation
}

// ClearAircrafts clears all "aircrafts" edges to the Aircraft entity.
func (auo *AirlineUpdateOne) ClearAircrafts() *AirlineUpdateOne {
	auo.mutation.ClearAircrafts()
	return auo
}

// RemoveAircraftIDs removes the "aircrafts" edge to Aircraft entities by IDs.
func (auo *AirlineUpdateOne) RemoveAircraftIDs(ids ...uuid.UUID) *AirlineUpdateOne {
	auo.mutation.RemoveAircraftIDs(ids...)
	return auo
}

// RemoveAircrafts removes "aircrafts" edges to Aircraft entities.
func (auo *AirlineUpdateOne) RemoveAircrafts(a ...*Aircraft) *AirlineUpdateOne {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return auo.RemoveAircraftIDs(ids...)
}

// ClearCrews clears all "crews" edges to the Crew entity.
func (auo *AirlineUpdateOne) ClearCrews() *AirlineUpdateOne {
	auo.mutation.ClearCrews()
	return auo
}

// RemoveCrewIDs removes the "crews" edge to Crew entities by IDs.
func (auo *AirlineUpdateOne) RemoveCrewIDs(ids ...uuid.UUID) *AirlineUpdateOne {
	auo.mutation.RemoveCrewIDs(ids...)
	return auo
}

// RemoveCrews removes "crews" edges to Crew entities.
func (auo *AirlineUpdateOne) RemoveCrews(c ...*Crew) *AirlineUpdateOne {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return auo.RemoveCrewIDs(ids...)
}

// ClearPilots clears all "pilots" edges to the Pilot entity.
func (auo *AirlineUpdateOne) ClearPilots() *AirlineUpdateOne {
	auo.mutation.ClearPilots()
	return auo
}

// RemovePilotIDs removes the "pilots" edge to Pilot entities by IDs.
func (auo *AirlineUpdateOne) RemovePilotIDs(ids ...uuid.UUID) *AirlineUpdateOne {
	auo.mutation.RemovePilotIDs(ids...)
	return auo
}

// RemovePilots removes "pilots" edges to Pilot entities.
func (auo *AirlineUpdateOne) RemovePilots(p ...*Pilot) *AirlineUpdateOne {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return auo.RemovePilotIDs(ids...)
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AirlineUpdateOne) Select(field string, fields ...string) *AirlineUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Airline entity.
func (auo *AirlineUpdateOne) Save(ctx context.Context) (*Airline, error) {
	var (
		err  error
		node *Airline
	)
	auo.defaults()
	if len(auo.hooks) == 0 {
		if err = auo.check(); err != nil {
			return nil, err
		}
		node, err = auo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AirlineMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = auo.check(); err != nil {
				return nil, err
			}
			auo.mutation = mutation
			node, err = auo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(auo.hooks) - 1; i >= 0; i-- {
			if auo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = auo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, auo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AirlineUpdateOne) SaveX(ctx context.Context) *Airline {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AirlineUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AirlineUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (auo *AirlineUpdateOne) defaults() {
	if _, ok := auo.mutation.UpdatedAt(); !ok {
		v := airline.UpdateDefaultUpdatedAt()
		auo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auo *AirlineUpdateOne) check() error {
	if v, ok := auo.mutation.Name(); ok {
		if err := airline.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf("ent: validator failed for field \"name\": %w", err)}
		}
	}
	if v, ok := auo.mutation.IataCode(); ok {
		if err := airline.IataCodeValidator(v); err != nil {
			return &ValidationError{Name: "iata_code", err: fmt.Errorf("ent: validator failed for field \"iata_code\": %w", err)}
		}
	}
	return nil
}

func (auo *AirlineUpdateOne) sqlSave(ctx context.Context) (_node *Airline, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   airline.Table,
			Columns: airline.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: airline.FieldID,
			},
		},
	}
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Airline.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, airline.FieldID)
		for _, f := range fields {
			if !airline.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != airline.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: airline.FieldName,
		})
	}
	if value, ok := auo.mutation.IataCode(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: airline.FieldIataCode,
		})
	}
	if value, ok := auo.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: airline.FieldCreatedAt,
		})
	}
	if value, ok := auo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: airline.FieldUpdatedAt,
		})
	}
	if auo.mutation.AircraftsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   airline.AircraftsTable,
			Columns: []string{airline.AircraftsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: aircraft.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedAircraftsIDs(); len(nodes) > 0 && !auo.mutation.AircraftsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   airline.AircraftsTable,
			Columns: []string{airline.AircraftsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: aircraft.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.AircraftsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   airline.AircraftsTable,
			Columns: []string{airline.AircraftsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: aircraft.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.CrewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   airline.CrewsTable,
			Columns: []string{airline.CrewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: crew.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedCrewsIDs(); len(nodes) > 0 && !auo.mutation.CrewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   airline.CrewsTable,
			Columns: []string{airline.CrewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: crew.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.CrewsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   airline.CrewsTable,
			Columns: []string{airline.CrewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: crew.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.PilotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   airline.PilotsTable,
			Columns: []string{airline.PilotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: pilot.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedPilotsIDs(); len(nodes) > 0 && !auo.mutation.PilotsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   airline.PilotsTable,
			Columns: []string{airline.PilotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: pilot.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.PilotsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   airline.PilotsTable,
			Columns: []string{airline.PilotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: pilot.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Airline{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{airline.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
