// Code generated by entc, DO NOT EDIT.

package ent

import (
	"airbound/internal/ent/enums"
	"airbound/internal/ent/flight"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// FlightCreate is the builder for creating a Flight entity.
type FlightCreate struct {
	config
	mutation *FlightMutation
	hooks    []Hook
}

// SetFlightNumber sets the "flight_number" field.
func (fc *FlightCreate) SetFlightNumber(s string) *FlightCreate {
	fc.mutation.SetFlightNumber(s)
	return fc
}

// SetDuration sets the "duration" field.
func (fc *FlightCreate) SetDuration(i int) *FlightCreate {
	fc.mutation.SetDuration(i)
	return fc
}

// SetDistance sets the "distance" field.
func (fc *FlightCreate) SetDistance(i int) *FlightCreate {
	fc.mutation.SetDistance(i)
	return fc
}

// SetBoardingPolicy sets the "boarding_policy" field.
func (fc *FlightCreate) SetBoardingPolicy(ep enums.BoardingPolicy) *FlightCreate {
	fc.mutation.SetBoardingPolicy(ep)
	return fc
}

// SetCreatedAt sets the "created_at" field.
func (fc *FlightCreate) SetCreatedAt(t time.Time) *FlightCreate {
	fc.mutation.SetCreatedAt(t)
	return fc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (fc *FlightCreate) SetNillableCreatedAt(t *time.Time) *FlightCreate {
	if t != nil {
		fc.SetCreatedAt(*t)
	}
	return fc
}

// SetUpdatedAt sets the "updated_at" field.
func (fc *FlightCreate) SetUpdatedAt(t time.Time) *FlightCreate {
	fc.mutation.SetUpdatedAt(t)
	return fc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (fc *FlightCreate) SetNillableUpdatedAt(t *time.Time) *FlightCreate {
	if t != nil {
		fc.SetUpdatedAt(*t)
	}
	return fc
}

// SetID sets the "id" field.
func (fc *FlightCreate) SetID(u uuid.UUID) *FlightCreate {
	fc.mutation.SetID(u)
	return fc
}

// Mutation returns the FlightMutation object of the builder.
func (fc *FlightCreate) Mutation() *FlightMutation {
	return fc.mutation
}

// Save creates the Flight in the database.
func (fc *FlightCreate) Save(ctx context.Context) (*Flight, error) {
	var (
		err  error
		node *Flight
	)
	fc.defaults()
	if len(fc.hooks) == 0 {
		if err = fc.check(); err != nil {
			return nil, err
		}
		node, err = fc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FlightMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = fc.check(); err != nil {
				return nil, err
			}
			fc.mutation = mutation
			if node, err = fc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(fc.hooks) - 1; i >= 0; i-- {
			if fc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = fc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, fc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (fc *FlightCreate) SaveX(ctx context.Context) *Flight {
	v, err := fc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fc *FlightCreate) Exec(ctx context.Context) error {
	_, err := fc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fc *FlightCreate) ExecX(ctx context.Context) {
	if err := fc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (fc *FlightCreate) defaults() {
	if _, ok := fc.mutation.CreatedAt(); !ok {
		v := flight.DefaultCreatedAt()
		fc.mutation.SetCreatedAt(v)
	}
	if _, ok := fc.mutation.UpdatedAt(); !ok {
		v := flight.DefaultUpdatedAt()
		fc.mutation.SetUpdatedAt(v)
	}
	if _, ok := fc.mutation.ID(); !ok {
		v := flight.DefaultID()
		fc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fc *FlightCreate) check() error {
	if _, ok := fc.mutation.FlightNumber(); !ok {
		return &ValidationError{Name: "flight_number", err: errors.New(`ent: missing required field "flight_number"`)}
	}
	if v, ok := fc.mutation.FlightNumber(); ok {
		if err := flight.FlightNumberValidator(v); err != nil {
			return &ValidationError{Name: "flight_number", err: fmt.Errorf(`ent: validator failed for field "flight_number": %w`, err)}
		}
	}
	if _, ok := fc.mutation.Duration(); !ok {
		return &ValidationError{Name: "duration", err: errors.New(`ent: missing required field "duration"`)}
	}
	if v, ok := fc.mutation.Duration(); ok {
		if err := flight.DurationValidator(v); err != nil {
			return &ValidationError{Name: "duration", err: fmt.Errorf(`ent: validator failed for field "duration": %w`, err)}
		}
	}
	if _, ok := fc.mutation.Distance(); !ok {
		return &ValidationError{Name: "distance", err: errors.New(`ent: missing required field "distance"`)}
	}
	if v, ok := fc.mutation.Distance(); ok {
		if err := flight.DistanceValidator(v); err != nil {
			return &ValidationError{Name: "distance", err: fmt.Errorf(`ent: validator failed for field "distance": %w`, err)}
		}
	}
	if _, ok := fc.mutation.BoardingPolicy(); !ok {
		return &ValidationError{Name: "boarding_policy", err: errors.New(`ent: missing required field "boarding_policy"`)}
	}
	if v, ok := fc.mutation.BoardingPolicy(); ok {
		if err := flight.BoardingPolicyValidator(v); err != nil {
			return &ValidationError{Name: "boarding_policy", err: fmt.Errorf(`ent: validator failed for field "boarding_policy": %w`, err)}
		}
	}
	if _, ok := fc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "created_at"`)}
	}
	if _, ok := fc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "updated_at"`)}
	}
	return nil
}

func (fc *FlightCreate) sqlSave(ctx context.Context) (*Flight, error) {
	_node, _spec := fc.createSpec()
	if err := sqlgraph.CreateNode(ctx, fc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		_node.ID = _spec.ID.Value.(uuid.UUID)
	}
	return _node, nil
}

func (fc *FlightCreate) createSpec() (*Flight, *sqlgraph.CreateSpec) {
	var (
		_node = &Flight{config: fc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: flight.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: flight.FieldID,
			},
		}
	)
	if id, ok := fc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := fc.mutation.FlightNumber(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: flight.FieldFlightNumber,
		})
		_node.FlightNumber = value
	}
	if value, ok := fc.mutation.Duration(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: flight.FieldDuration,
		})
		_node.Duration = value
	}
	if value, ok := fc.mutation.Distance(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: flight.FieldDistance,
		})
		_node.Distance = value
	}
	if value, ok := fc.mutation.BoardingPolicy(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: flight.FieldBoardingPolicy,
		})
		_node.BoardingPolicy = value
	}
	if value, ok := fc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: flight.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := fc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: flight.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// FlightCreateBulk is the builder for creating many Flight entities in bulk.
type FlightCreateBulk struct {
	config
	builders []*FlightCreate
}

// Save creates the Flight entities in the database.
func (fcb *FlightCreateBulk) Save(ctx context.Context) ([]*Flight, error) {
	specs := make([]*sqlgraph.CreateSpec, len(fcb.builders))
	nodes := make([]*Flight, len(fcb.builders))
	mutators := make([]Mutator, len(fcb.builders))
	for i := range fcb.builders {
		func(i int, root context.Context) {
			builder := fcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FlightMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, fcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, fcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, fcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (fcb *FlightCreateBulk) SaveX(ctx context.Context) []*Flight {
	v, err := fcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fcb *FlightCreateBulk) Exec(ctx context.Context) error {
	_, err := fcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fcb *FlightCreateBulk) ExecX(ctx context.Context) {
	if err := fcb.Exec(ctx); err != nil {
		panic(err)
	}
}
