// Code generated by entc, DO NOT EDIT.

package ent

import (
	"airbound/internal/ent/airline"
	"airbound/internal/ent/pilot"
	"airbound/internal/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Pilot is the model entity for the Pilot schema.
type Pilot struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// EmployeeID holds the value of the "employee_id" field.
	EmployeeID string `json:"employee_id,omitempty"`
	// LicenceNumber holds the value of the "licence_number" field.
	LicenceNumber string `json:"licence_number,omitempty"`
	// FlightHours holds the value of the "flight_hours" field.
	FlightHours int `json:"flight_hours,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PilotQuery when eager-loading is set.
	Edges      PilotEdges `json:"edges"`
	airline_id *uuid.UUID
	user_pilot *uuid.UUID
}

// PilotEdges holds the relations/edges for other nodes in the graph.
type PilotEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Airline holds the value of the airline edge.
	Airline *Airline `json:"airline,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PilotEdges) UserOrErr() (*User, error) {
	if e.loadedTypes[0] {
		if e.User == nil {
			// The edge user was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// AirlineOrErr returns the Airline value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PilotEdges) AirlineOrErr() (*Airline, error) {
	if e.loadedTypes[1] {
		if e.Airline == nil {
			// The edge airline was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: airline.Label}
		}
		return e.Airline, nil
	}
	return nil, &NotLoadedError{edge: "airline"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Pilot) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case pilot.FieldFlightHours:
			values[i] = new(sql.NullInt64)
		case pilot.FieldEmployeeID, pilot.FieldLicenceNumber:
			values[i] = new(sql.NullString)
		case pilot.FieldCreatedAt, pilot.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case pilot.FieldID:
			values[i] = new(uuid.UUID)
		case pilot.ForeignKeys[0]: // airline_id
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case pilot.ForeignKeys[1]: // user_pilot
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			return nil, fmt.Errorf("unexpected column %q for type Pilot", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Pilot fields.
func (pi *Pilot) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pilot.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				pi.ID = *value
			}
		case pilot.FieldEmployeeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field employee_id", values[i])
			} else if value.Valid {
				pi.EmployeeID = value.String
			}
		case pilot.FieldLicenceNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field licence_number", values[i])
			} else if value.Valid {
				pi.LicenceNumber = value.String
			}
		case pilot.FieldFlightHours:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field flight_hours", values[i])
			} else if value.Valid {
				pi.FlightHours = int(value.Int64)
			}
		case pilot.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				pi.CreatedAt = value.Time
			}
		case pilot.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				pi.UpdatedAt = value.Time
			}
		case pilot.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field airline_id", values[i])
			} else if value.Valid {
				pi.airline_id = new(uuid.UUID)
				*pi.airline_id = *value.S.(*uuid.UUID)
			}
		case pilot.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_pilot", values[i])
			} else if value.Valid {
				pi.user_pilot = new(uuid.UUID)
				*pi.user_pilot = *value.S.(*uuid.UUID)
			}
		}
	}
	return nil
}

// QueryUser queries the "user" edge of the Pilot entity.
func (pi *Pilot) QueryUser() *UserQuery {
	return (&PilotClient{config: pi.config}).QueryUser(pi)
}

// QueryAirline queries the "airline" edge of the Pilot entity.
func (pi *Pilot) QueryAirline() *AirlineQuery {
	return (&PilotClient{config: pi.config}).QueryAirline(pi)
}

// Update returns a builder for updating this Pilot.
// Note that you need to call Pilot.Unwrap() before calling this method if this Pilot
// was returned from a transaction, and the transaction was committed or rolled back.
func (pi *Pilot) Update() *PilotUpdateOne {
	return (&PilotClient{config: pi.config}).UpdateOne(pi)
}

// Unwrap unwraps the Pilot entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pi *Pilot) Unwrap() *Pilot {
	tx, ok := pi.config.driver.(*txDriver)
	if !ok {
		panic("ent: Pilot is not a transactional entity")
	}
	pi.config.driver = tx.drv
	return pi
}

// String implements the fmt.Stringer.
func (pi *Pilot) String() string {
	var builder strings.Builder
	builder.WriteString("Pilot(")
	builder.WriteString(fmt.Sprintf("id=%v", pi.ID))
	builder.WriteString(", employee_id=")
	builder.WriteString(pi.EmployeeID)
	builder.WriteString(", licence_number=")
	builder.WriteString(pi.LicenceNumber)
	builder.WriteString(", flight_hours=")
	builder.WriteString(fmt.Sprintf("%v", pi.FlightHours))
	builder.WriteString(", created_at=")
	builder.WriteString(pi.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", updated_at=")
	builder.WriteString(pi.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Pilots is a parsable slice of Pilot.
type Pilots []*Pilot

func (pi Pilots) config(cfg config) {
	for _i := range pi {
		pi[_i].config = cfg
	}
}
